[build]
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "20"

# 1) Proxy API -> backend Render (doit être AVANT la règle SPA)
[[redirects]]
  from = "/api/*"
  to   = "https://corep-tracker-api.onrender.com/api/:splat"
  status = 200
  force = true

# 2) Fallback SPA (garde-la en dernier)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
  